package br.com.cactusdigital.erp.cadastros.model;

import java.io.Serializable;

/**
 * @author Antonio
 *
 */
public class PessoaFisica implements Serializable {

	/**
	 * Serial UID
	 */
	private static final long serialVersionUID = -8850799133679101763L;
	
//	CODIGO INTEGER PRIMARY KEY AUTO_INCREMENT,
//	CPF VARCHAR(20) NOT NULL,
//	RG VARCHAR(20) NOT NULL,
//	ORGAO_RG VARCHAR(10),
//	DATA_EMISSAO_RG DATE,
//	DATA_NASCIMENTO DATE NOT NULL,
//	TIPO_SEXO CHAR(1) NOT NULL,
//	NATURALIDADE VARCHAR(50),
//	NACIONALIDADE VARCHAR(50),
//	TIPO_RACA VARCHAR(20),
//	TIPO_SANGUE VARCHAR(10),
//	CNH_NUMERO VARCHAR(20),
//	CNH_CATEGORIA VARCHAR(5),
//	CNH_VENCIMENTO DATE,
//	TITULO_ELEITORAL_NUMERO VARCHAR(20),
//	TITULO_ELEITORAL_ZONA INTEGER,
//	TITULO_ELEITORAL_SESSAO INTEGER,
//	RESERVISTA_NUMERO VARCHAR(30),
//	RESERVISTA_CATEGORIA INTEGER,
//	NOME_MAE VARCHAR(100),
//	NOME_PAI VARCHAR(100),
//	CODIGO_ESTADO_CIVIL INTEGER NOT NULL,
//	CODIGO_PESSOA INTEGER NOT NULL,

}
